version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
    stdin_open: true
    tty: true
    command: npm start

  backend:
    container_name: backend
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend

  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6379:6379'

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
